# Docker compose for local use.
version: "3"

volumes:
  my_dbdata: { }

services:
  demo-db:
    image: "postgres"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
  adminer:
    image: adminer:standalone
    container_name: adminer
    ports:
      - "8079:8080"
