spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: demo
    password: demo
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    ddl-auto: create


management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: '*'


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  group-configs:
    - group: score
      paths-to-match: /score/**
